name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Seiraruth
          filename: github-metrics.svg

          template: classic
          base: header, activity, community, repositories, metadata

          # config_display: columns
          # config_padding: 8, 12
          config_timezone: Asia/Bangkok

          # Contributions calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Lines of code pushed
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_repositories_limit: 10
          plugin_lines_history_limit: 1

          # Language stats
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes

          # Recently starred repos
          plugin_stars: yes
          plugin_stars_limit: 4

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C

          # LeetCode (optional)
          plugin_leetcode: yes
          plugin_leetcode_user: Seiraruth
          plugin_leetcode_sections: solved, skills, recent
