name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Seiraruth
          filename: github-metrics.svg

          template: classic
          # Keep only minimal base panels
          base: header, activity
          config_timezone: Asia/Bangkok

          # Contributions calendar (3D isometric)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Lines of code pushed
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_repositories_limit: 10
          plugin_lines_history_limit: 1

          # Contributions in years 

          plugin_calendar: yes
          plugin_calendar_limit: 5

          # Recently starred repositories
          plugin_stars: yes
          plugin_stars_limit: 4
